SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for satu_sehat_ref_numerator
-- Sumber: UCUM (Unified Code for Units of Measure) — http://unitsofmeasure.org
-- System: http://unitsofmeasure.org
-- ----------------------------
DROP TABLE IF EXISTS `satu_sehat_ref_numerator`;
CREATE TABLE `satu_sehat_ref_numerator` (
  `code`    varchar(80)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `display` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=Dynamic;

-- ----------------------------
-- Records of satu_sehat_ref_numerator (UCUM)
-- ----------------------------
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10.L/min', '10 liter per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10.L/(min.m2)', '10 liter per minute per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10.uN.s/(cm5.m2)', '10 micronewton second per centimeter to the fifth power per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*4/uL', '10 thousand per microliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*8', '100 million');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('24.h', '24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{absorbance}', 'absorbance');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{activity}', 'activity');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[AU]', 'allergy unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{AHF''U}', 'American Hospital Formulary unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('A', 'ampere');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('A/m', 'ampere per meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[arb''U]', 'arbitrary unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[arb''U]/mL', 'arbitrary unit per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{ARU}', 'aspirin response unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('atm', 'atmosphere');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ag/{cell}', 'attogram per cell');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('bar', 'bar');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('Bq', 'Becquerel');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[beth''U]', 'Bethesda unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*9/L', 'billion per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*9/uL', 'billion per microliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*9/mL', 'billion per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{binding_index}', 'binding index');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[bdsk''U]', 'Bodansky unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{breaths}/min', 'breaths per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cal', 'calorie');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{cells}', 'cells');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{cells}/[HPF]', 'cells per high power field');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{cells}/uL', 'cells per microliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cg', 'centigram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cL', 'centiliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cm', 'centimeter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cm[Hg]', 'centimeter of mercury');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cm[H2O]', 'centimeter of water');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cm[H2O]/L/s', 'centimeter of water per liter per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cm[H2O]/s/m', 'centimeter of water per second per meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cm/s', 'centimeter per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cP', 'centipoise');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cSt', 'centistoke');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{CFU}', 'colony forming unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[CFU]/L', 'colony forming unit per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[CFU]/mL', 'colony forming unit per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{copies}', 'copies');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{copies}/ug', 'copies per microgram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{copies}/mL', 'copies per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{count}', 'count');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cm3', 'cubic centimeter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('m3/s', 'cubic meter per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('d', 'day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('d/wk', 'days per week');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('dB', 'decibel');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('dg', 'decigram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('dL', 'deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('dm', 'decimeter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('deg', 'degree (plane angle)');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('Cel', 'degree Celsius');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[degF]', 'degree Fahrenheit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('K', 'degree Kelvin');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('deg/s', 'degree per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('daL/min', 'dekaliter per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('daL/min/m2', 'dekaliter per minute per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[diop]', 'diopter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[drp]', 'drop (1/12 milliliter)');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{EIA''U}', 'EIA unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('eV', 'electron Volt');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U', 'enzyme unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/10', 'enzyme unit per 10');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/(24.h)', 'enzyme unit per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/d', 'enzyme unit per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/dL', 'enzyme unit per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/g', 'enzyme unit per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/g{creat}', 'enzyme unit per gram of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/g{Hb}', 'enzyme unit per gram of hemoglobin');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/h', 'enzyme unit per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/kg', 'enzyme unit per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/L', 'enzyme unit per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/mL', 'enzyme unit per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/min', 'enzyme unit per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('U/s', 'enzyme unit per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('eq', 'equivalent');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('eq/L', 'equivalent per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('eq/mL', 'equivalent per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('fg', 'femtogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('fL', 'femtoliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('fm', 'femtometer');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('fmol', 'femtomole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('fmol/g', 'femtomole per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('fmol/L', 'femtomole per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('fmol/mg', 'femtomole per milligram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('fmol/mL', 'femtomole per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g', 'gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/(100.g)', 'gram per 100 gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/(12.h)', 'gram per 12 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/(24.h)', 'gram per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/cm3', 'gram per cubic centimeter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/d', 'gram per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/dL', 'gram per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/g', 'gram per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/g{creat}', 'gram per gram of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/h', 'gram per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/kg', 'gram per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/kg/d', 'gram per kilogram per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/kg/h', 'gram per kilogram per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/kg/min', 'gram per kilogram per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/L', 'gram per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/mg', 'gram per milligram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/mL', 'gram per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/mmol', 'gram per millimole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/min', 'gram per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('g/m2', 'gram per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[beats}/min', 'heart beats per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('Hz', 'Hertz');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('h', 'hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('h/d', 'hour per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[IU]', 'international unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[IU]/(24.h)', 'international unit per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[IU]/d', 'international unit per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[IU]/dL', 'international unit per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[IU]/g', 'international unit per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[IU]/h', 'international unit per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[IU]/kg', 'international unit per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[IU]/kg/d', 'international unit per kilogram per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[IU]/L', 'international unit per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[IU]/mL', 'international unit per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[IU]/min', 'international unit per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('J', 'joule');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('J/L', 'joule per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kat', 'katal');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kat/kg', 'katal per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kat/L', 'katal per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kU', 'kilo enzyme unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kU/g', 'kilo enzyme unit per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kU/L', 'kilo enzyme unit per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kU/mL', 'kilo enzyme unit per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('k[IU]/L', 'kilo international unit per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('k[IU]/mL', 'kilo international unit per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kcal', 'kilocalorie');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kcal/d', 'kilocalorie per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kcal/h', 'kilocalorie per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kcal/kg/(24.h)', 'kilocalorie per kilogram per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kg', 'kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kg/m3', 'kilogram per cubic meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kg/h', 'kilogram per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kg/L', 'kilogram per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kg/min', 'kilogram per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kg/mol', 'kilogram per mole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kg/s', 'kilogram per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kg/m2', 'kilogram per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kL', 'kiloliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('km', 'kilometer');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('kPa', 'kilopascal');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('L', 'liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('L/(24.h)', 'liter per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('L/d', 'liter per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('L/h', 'liter per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('L/kg', 'liter per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('L/L', 'liter per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('L/min', 'liter per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('L/(min.m2)', 'liter per minute per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('L/s', 'liter per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{Log}', 'log base 10');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{Log_copies}/mL', 'log (base 10) copies per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{Log_IU}', 'log (base 10) international unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{Log_IU}/mL', 'log (base 10) international unit per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('m', 'meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('m/s', 'meter per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('m/s2', 'meter per square second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('t', 'metric ton');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('uU/g', 'micro enzyme unit per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('uU/L', 'micro enzyme unit per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('uU/mL', 'micro enzyme unit per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('u[IU]', 'micro international unit');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('u[IU]/mL', 'micro international unit per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('u[IU]/L', 'microinternational unit per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ueq', 'microequivalent');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ueq/L', 'microequivalent per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ueq/mL', 'microequivalent per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug', 'microgram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/(24.h)', 'microgram per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/m3', 'microgram per cubic meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/d', 'microgram per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/dL', 'microgram per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/g', 'microgram per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/g{creat}', 'microgram per gram of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/g{Hb}', 'microgram per gram of hemoglobin');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/h', 'microgram per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/kg', 'microgram per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/kg/d', 'microgram per kilogram per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/kg/h', 'microgram per kilogram per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/kg/min', 'microgram per kilogram per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/L', 'microgram per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/mg', 'microgram per milligram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/mg{creat}', 'microgram per milligram of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/mL', 'microgram per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/mmol', 'microgram per millimole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/min', 'microgram per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ug/m2', 'microgram per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ukat', 'microkatal');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('uL', 'microliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('uL/h', 'microliter per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('um', 'micrometer');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol', 'micromole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/(24.h)', 'micromole per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/d', 'micromole per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/dL', 'micromole per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/g', 'micromole per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/g{creat}', 'micromole per gram of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/g{Hb}', 'micromole per gram of hemoglobin');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/h', 'micromole per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/kg', 'micromole per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/L', 'micromole per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/L/h', 'micromole per liter per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/umol', 'micromole per micromole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/mg', 'micromole per milligram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/mL', 'micromole per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/mL/min', 'micromole per milliliter per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/mmol', 'micromole per millimole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/min', 'micromole per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/min/g', 'micromole per minute per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/min/L', 'micromole per minute per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('umol/mol', 'micromole per mole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('um/s', 'microns per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('us', 'microsecond');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('uV', 'microvolt');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mU/g', 'milli enzyme unit per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mU/mL', 'milli enzyme unit per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mU/mmol{creat}', 'milli enzyme unit per millimole of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mU/L', 'milli enzyme unit per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mU/mg', 'milli enzyme unit per milligram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('m[IU]/mL', 'milli international unit per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('m[IU]/L', 'milli international unit per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mA', 'milliampere');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mbar', 'millibar');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mbar/L/s', 'millibar per liter per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('meq', 'milliequivalent');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('meq/(24.h)', 'milliequivalent per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('meq/d', 'milliequivalent per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('meq/dL', 'milliequivalent per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('meq/g', 'milliequivalent per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('meq/h', 'milliequivalent per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('meq/kg', 'milliequivalent per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('meq/kg/h', 'milliequivalent per kilogram per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('meq/L', 'milliequivalent per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('meq/mL', 'milliequivalent per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('meq/min', 'milliequivalent per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('meq/m2', 'milliequivalent per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg', 'milligram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/(12.h)', 'milligram per 12 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/(24.h)', 'milligram per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/m3', 'milligram per cubic meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/d', 'milligram per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/dL', 'milligram per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/g', 'milligram per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/g{creat}', 'milligram per gram of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/h', 'milligram per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/kg', 'milligram per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/kg/d', 'milligram per kilogram per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/kg/h', 'milligram per kilogram per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/kg/min', 'milligram per kilogram per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/L', 'milligram per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/mg', 'milligram per milligram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/mg{creat}', 'milligram per milligram of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/mL', 'milligram per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/mmol', 'milligram per millimole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/min', 'milligram per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/m2', 'milligram per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mg/wk', 'milligram per week');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL', 'milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/(12.h)', 'milliliter per 12 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/(24.h)', 'milliliter per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/cm[H2O]', 'milliliter per centimeter of water');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/d', 'milliliter per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/dL', 'milliliter per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/{beat}', 'milliliter per heart beat');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/h', 'milliliter per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/kg', 'milliliter per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/kg/d', 'milliliter per kilogram per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/kg/h', 'milliliter per kilogram per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/kg/min', 'milliliter per kilogram per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/mbar', 'milliliter per millibar');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/min', 'milliliter per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/min/{1.73_m2}', 'milliliter per minute per 1.73 square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/min/m2', 'milliliter per minute per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/s', 'milliliter per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mL/m2', 'milliliter per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mm', 'millimeter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mm[Hg]', 'millimeter of mercury');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mm[H2O]', 'millimeter of water');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mm/h', 'millimeter per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mm/min', 'millimeter per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol', 'millimole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/(12.h)', 'millimole per 12 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/(24.h)', 'millimole per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/d', 'millimole per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/dL', 'millimole per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/g', 'millimole per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/g{creat}', 'millimole per gram of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/h', 'millimole per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/kg', 'millimole per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/kg/d', 'millimole per kilogram per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/kg/h', 'millimole per kilogram per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/kg/min', 'millimole per kilogram per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/L', 'millimole per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/mmol', 'millimole per millimole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/min', 'millimole per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/mol', 'millimole per mole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/s/L', 'millimole per second per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mmol/m2', 'millimole per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mosm', 'milliosmole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mosm/kg', 'milliosmole per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mosm/L', 'milliosmole per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mPa', 'millipascal');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ms', 'millisecond');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mV', 'millivolt');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{minidrop}/min', 'minidrop per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('min', 'minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('min/d', 'minute per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('min/wk', 'minute per week');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mol', 'mole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mol/m3', 'mole per cubic meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mol/kg', 'mole per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mol/L', 'mole per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mol/mL', 'mole per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mol/mol', 'mole per mole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mol/s', 'mole per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mo', 'month');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nU/mL', 'nanoenzyme unit per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng', 'nanogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/(24.h)', 'nanogram per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/d', 'nanogram per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/dL', 'nanogram per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/g', 'nanogram per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/h', 'nanogram per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/kg', 'nanogram per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/kg/h', 'nanogram per kilogram per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/kg/min', 'nanogram per kilogram per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/L', 'nanogram per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/mg', 'nanogram per milligram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/mL', 'nanogram per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/min', 'nanogram per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/s', 'nanogram per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ng/m2', 'nanogram per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nkat', 'nanokatal');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nL', 'nanoliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nm', 'nanometer');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol', 'nanomole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/(24.h)', 'nanomole per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/d', 'nanomole per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/dL', 'nanomole per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/g', 'nanomole per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/h/mg{prot}', 'nanomole per hour per milligram of protein');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/L', 'nanomole per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/umol{creat}', 'nanomole per micromole of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/mg', 'nanomole per milligram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/mg{creat}', 'nanomole per milligram of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/mg{prot}', 'nanomole per milligram of protein');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/mL', 'nanomole per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/mL/min', 'nanomole per milliliter per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/mmol', 'nanomole per millimole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/mmol{creat}', 'nanomole per millimole of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/min', 'nanomole per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/min/mg{prot}', 'nanomole per minute per milligram of protein');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/min/mL', 'nanomole per minute per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/mol', 'nanomole per mole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/mol{creat}', 'nanomole per mole creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/s', 'nanomole per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('nmol/s/L', 'nanomole per second per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('ns', 'nanosecond');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('N', 'Newton');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('N.cm', 'Newton centimeter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{#}', 'number');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{#}/d', 'number per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{#}/g', 'number per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{#}/[HPF]', 'number per high power field');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{#}/L', 'number per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{#}/uL', 'number per microliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{#}/mL', 'number per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{#}/min', 'number per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('Ohm', 'Ohm');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('osm', 'osmole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('osm/kg', 'osmole per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('osm/L', 'osmole per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[oz_av]', 'ounce (US and British)');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('Pa', 'Pascal');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/10*10', 'per 10 billion');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/100', 'per 100');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/100{cells}', 'per 100 cells');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/100{WBCs}', 'per 100 white blood cells');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/10*9', 'per billion');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/d', 'per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/dL', 'per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/g', 'per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/h', 'per hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/kg', 'per kilogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/L', 'per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/uL', 'per microliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/mg', 'per milligram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/mL', 'per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/mm', 'per millimeter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/10*6', 'per million');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/min', 'per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/mo', 'per month');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/s', 'per second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/m2', 'per square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/10*3', 'per thousand');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/10*12', 'per trillion');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/wk', 'per week');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('/a', 'per year');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('%', 'percent');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('%{activity}', 'percent activity');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('%{binding}', 'percent binding');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('%{Hb}', 'percent hemoglobin');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('%{inhibition}', 'percent inhibition');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('%{normal}', 'percent normal');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('%{saturation}', 'percent saturation');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('%{total}', 'percent total');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[pH]', 'pH');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pA', 'picoampere');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pg', 'picogram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pg/{cell}', 'picogram per cell');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pg/dL', 'picogram per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pg/L', 'picogram per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pg/mL', 'picogram per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pkat', 'picokatal');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pL', 'picoliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pm', 'picometer');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pmol', 'picomole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pmol/(24.h)', 'picomole per 24 hour');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pmol/d', 'picomole per day');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pmol/dL', 'picomole per deciliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pmol/g', 'picomole per gram');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pmol/L', 'picomole per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pmol/umol', 'picomole per micromole');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pmol/mg{prot}', 'picomole per milligram of protein');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pmol/mL', 'picomole per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pmol/mmol{creat}', 'picomole per millimole of creatinine');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('pmol/min', 'picomole per minute');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[lb_av]', 'pound (US and British)');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{ratio}', 'ratio');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{risk}', 'risk');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{saturation}', 'saturation');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{score}', 'score');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('s', 'second');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('S', 'Siemens');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('Sv', 'Sievert');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{spermatozoa}/mL', 'spermatozoa per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('cm2', 'square centimeter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('m2', 'square meter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('mm2', 'square millimeter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[tbs_us]', 'tablespoon (US)');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('[tsp_us]', 'teaspoon (US)');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('T', 'Tesla');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*3', 'thousand');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*3{copies}/mL', 'thousand copies per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*3/L', 'thousand per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*3/uL', 'thousand per microliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*3/mL', 'thousand per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{titer}', 'titer');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('Torr', 'Torr');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*12/L', 'trillion per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('V', 'volt');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('wk', 'week');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('a', 'year');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('{Zscore}', 'z score');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*6', 'million');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*6/L', 'million per liter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*6/uL', 'million per microliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*6/mL', 'million per milliliter');
INSERT INTO `satu_sehat_ref_numerator` VALUES ('10*5', 'one hundred thousand');

SET FOREIGN_KEY_CHECKS = 1;
